### ISSUE TITLE
Error when running migrations

### ISSUE THREAD

**Issue by moetanahy** [MasterRO94/laravel-mail-viewer#19]
Hi,

Firstly, thanks for an excellent library.  We use this regularly as it helps to debug issues on sending mails from one of our platforms.

I have just done an upgrade to the latest version, but I'm getting the following error

INFO  Running migrations.
2022_02_11_013354_add_payload_column_to_mail_logs
 2022_02_11_013396_make_json_fields
22,393ms FAIL
In Connection.php line 760:
SQLSTATE[22032]: <<Unknown error>>: 3140 Invalid JSON text: "Invalid value.
" at position 0 in value for column '#sql-12dce_258b5.headers'. (SQL: ALTER
TABLE mail_logs CHANGE headers headers JSON DEFAULT NULL, CHANGE attachmen
ts attachments JSON DEFAULT NULL)
In Connection.php line 545:
SQLSTATE[22032]: <<Unknown error>>: 3140 Invalid JSON text: "Invalid value.
" at position 0 in value for column '#sql-12dce_258b5.headers'.

I've run this locally and it works fine, but on an environment with lots of data in, this happens.  Any ideas what this issue is related to?

**Comment by moetanahy** [comment]
To add more color to this, we discovered this issue occurs on MySQL 8 (specifically from 8.0.23 to 8.0.32 - we tried both).  However, MariaDB 10 has no issues with the migration.

The issue is specifically with this migration - 2022_02_11_013396_make_json_fields

**Comment by MasterRO94** [comment]
Hi @moetanahy 
Thanks for the issue.
Could you provide a a couple of rows with your data to reproduce the issue. Of course, you can redact it. 
You can send data to my email igoshin18@gmail.com
